# ===================================
#  Relation Behavior Config
# ===================================

clusters:
    label: 'initbiz.cumuluscore::lang.cluster.cluster'
    view:
        list: $/initbiz/cumuluscore/models/cluster/related_columns.yaml
        toolbarButtons: add|remove
        showSearch: true
