include:
    - component: $CI_SERVER_FQDN/operational/gitlab-ci-components/setup-project-playground-user-3@1.4.2
      inputs:
          octobercms_license_key: "${PLAYGROUND_LICENSE_KEY}"
          github_machine_user_token: ${GITHUB_MACHINE_USER_TOKEN}
    - component: $CI_SERVER_FQDN/operational/gitlab-ci-components/rules-mr-events@1
    - component: $CI_SERVER_FQDN/operational/gitlab-ci-components/danger@1

Tests:
    extends:
        - .rules-mr-events
        - .setup-project-playground
    script:
        - composer require initbiz/cumuluscore-plugin:dev-${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}
        - vendor/bin/pest --parallel --ci --bail

Linter:
    extends:
        - .rules-mr-events
        - .setup-project-playground
    script:
        - composer require initbiz/cumuluscore-plugin:dev-${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}
        - php artisan linter:code -b plugins/initbiz/cumuluscore

Danger-PHP:
    extends:
        - .danger
        - .rules-mr-events
