include:
    - component: $CI_SERVER_FQDN/operational/gitlab-ci-components/setup-project-playground@1
      inputs:
          octobercms_license_key: "${PLAYGROUND_LICENSE_KEY}"
          github_machine_user_token: ${GITHUB_MACHINE_USER_TOKEN}
    - component: $CI_SERVER_FQDN/operational/gitlab-ci-components/setup-project-playground-october-3@1
      inputs:
          octobercms_license_key: "${PLAYGROUND_LICENSE_KEY}"
          github_machine_user_token: ${GITHUB_MACHINE_USER_TOKEN}
    - component: $CI_SERVER_FQDN/operational/gitlab-ci-components/rules-mr-events@1
    - component: $CI_SERVER_FQDN/operational/gitlab-ci-components/danger@1

Tests:
    extends:
        - .rules-mr-events
        - .setup-project-playground
    script:
        - composer require initbiz/cumulusroles-plugin:dev-feature/3869-oc-4
        - composer require "initbiz/cumuluscore-plugin:dev-${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME} as 3.22.1"
        - vendor/bin/pest --parallel --ci --bail

Tests-october-3:
    extends:
        - .rules-mr-events
        - .setup-project-playground-october-3
    script:
        - composer require "initbiz/cumuluscore-plugin:dev-${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME} as 3.22.1"
        - vendor/bin/pest --parallel --ci --bail

Linter:
    extends:
        - .rules-mr-events
        - .setup-project-playground
    script:
        - composer require initbiz/cumulusroles-plugin:dev-feature/3869-oc-4
        - composer require "initbiz/cumuluscore-plugin:dev-${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME} as 3.22.1"
        - php artisan linter:code -b plugins/initbiz/cumuluscore

Danger-PHP:
    extends:
        - .danger
        - .rules-mr-events
