plugin:
    homepage: 'https://cumulus.init.biz'
permissions:
    initbiz.cumuluscore.settings_general:
        tab: 'initbiz.cumuluscore::lang.permissions.cumulus_tab'
        label: 'initbiz.cumuluscore::lang.permissions.settings_access_general'
    initbiz.cumuluscore.settings_access_auto_assign:
        tab: 'initbiz.cumuluscore::lang.permissions.cumulus_tab'
        label: 'initbiz.cumuluscore::lang.permissions.settings_access_auto_assign'
    initbiz.cumuluscore.settings_access_manage_features:
        tab: 'initbiz.cumuluscore::lang.permissions.cumulus_tab'
        label: 'initbiz.cumuluscore::lang.permissions.settings_access_manage_features'
    initbiz.cumuluscore.access_users:
        tab: 'initbiz.cumuluscore::lang.permissions.cumulus_tab'
        label: 'initbiz.cumuluscore::lang.permissions.access_users'
    initbiz.cumuluscore.access_clusters:
        tab: 'initbiz.cumuluscore::lang.permissions.cumulus_tab'
        label: 'initbiz.cumuluscore::lang.permissions.access_clusters'
    initbiz.cumuluscore.access_plans:
        tab: 'initbiz.cumuluscore::lang.permissions.cumulus_tab'
        label: 'initbiz.cumuluscore::lang.permissions.access_plans'
navigation:
    cumulus-main-menu:
        label: 'initbiz.cumuluscore::lang.navigation.main'
        url: initbiz/cumuluscore/dashboard
        icon: icon-cloud
        permissions:
            0: 'initbiz.cumuluscore.access*'
        order: '700'
        sideMenu:
            cumulus-side-menu-users:
                label: 'initbiz.cumuluscore::lang.navigation.users'
                url: initbiz/cumuluscore/users
                icon: icon-users
                permissions:
                    0: 'initbiz.cumuluscore.access_users'
            cumulus-side-menu-clusters:
                label: 'initbiz.cumuluscore::lang.navigation.clusters'
                url: initbiz/cumuluscore/clusters
                icon: icon-building
                permissions:
                    0: 'initbiz.cumuluscore.access_clusters'
            cumulus-side-menu-plan:
                label: 'initbiz.cumuluscore::lang.navigation.plans'
                url: initbiz/cumuluscore/plans
                icon: icon-map
                permissions:
                    0: 'initbiz.cumuluscore.access_plans'
